USE PropertyManagement;
GO

-- ✅ Drop foreign key constraints first
ALTER TABLE Payments DROP CONSTRAINT IF EXISTS FK_Payments_Tenants;
GO
ALTER TABLE Payments DROP CONSTRAINT IF EXISTS FK_Payments_PaymentMethods;
GO
ALTER TABLE Tenants DROP CONSTRAINT IF EXISTS FK_Tenants_Users;
GO
ALTER TABLE Tenants DROP CONSTRAINT IF EXISTS FK_Tenants_Property;
GO
ALTER TABLE PropertyOwners DROP CONSTRAINT IF EXISTS FK_PropertyOwners_Owners;
GO
ALTER TABLE PropertyOwners DROP CONSTRAINT IF EXISTS FK_PropertyOwners_Property;
GO
ALTER TABLE RolePermissions DROP CONSTRAINT IF EXISTS FK_RolePermissions_Roles;
GO
ALTER TABLE RolePermissions DROP CONSTRAINT IF EXISTS FK_RolePermissions_Permissions;
GO
ALTER TABLE Users DROP CONSTRAINT IF EXISTS FK_Users_Roles;
GO

-- ✅ Drop tables with dependencies first
DROP TABLE IF EXISTS Payments;
GO
DROP TABLE IF EXISTS lkupPaymentMethods;
GO
DROP TABLE IF EXISTS PropertyOwners;
GO
DROP TABLE IF EXISTS Owners;
GO
DROP TABLE IF EXISTS Pricing;
GO
DROP TABLE IF EXISTS Property;
GO
DROP TABLE IF EXISTS Tenants;
GO
DROP TABLE IF EXISTS Users;
GO
DROP TABLE IF EXISTS RolePermissions;
GO
DROP TABLE IF EXISTS Permissions;
GO
DROP TABLE IF EXISTS Roles;
GO

-- ✅ Drop remaining tables
DROP TABLE IF EXISTS PaymentReminders;
GO
DROP TABLE IF EXISTS Documents;
GO
DROP TABLE IF EXISTS DocumentStorage;
GO
DROP TABLE IF EXISTS Notes;
GO
DROP TABLE IF EXISTS Invoices;
GO
DROP TABLE IF EXISTS Leases;
GO
DROP TABLE IF EXISTS PropertyPhotos;
GO
DROP TABLE IF EXISTS AccessLogs;
GO
DROP TABLE IF EXISTS MaintenanceRequests;
GO
DROP TABLE IF EXISTS Emails;
GO
DROP TABLE IF EXISTS SpecialInstructions;
GO
DROP TABLE IF EXISTS BillingAddress;
GO
DROP TABLE IF EXISTS CreditCardInfo;
GO
DROP TABLE IF EXISTS Vendors;
GO
DROP TABLE IF EXISTS lkupCreditCards;
GO
DROP TABLE IF EXISTS lkupMaintenanceRequestTypes;
GO
DROP TABLE IF EXISTS lkupPropertyRooms;
GO
DROP TABLE IF EXISTS lkupInvoiceType;
GO
DROP TABLE IF EXISTS lkupServiceTypes;
GO
DROP TABLE IF EXISTS lkupDocumentType;
GO
DROP TABLE IF EXISTS lkupCategory;
GO