USE [PropertyManagement];
GO

-- ✅ Drop tables with foreign key dependencies first
DROP TABLE IF EXISTS PaymentReminders;
DROP TABLE IF EXISTS Documents;
DROP TABLE IF EXISTS Notes;
DROP TABLE IF EXISTS Invoices;
DROP TABLE IF EXISTS Leases;
DROP TABLE IF EXISTS PropertyPhotos;
DROP TABLE IF EXISTS AccessLogs;
DROP TABLE IF EXISTS MaintenanceRequests;
DROP TABLE IF EXISTS Emails;
DROP TABLE IF EXISTS SpecialInstructions;
DROP TABLE IF EXISTS BillingAddress;
DROP TABLE IF EXISTS CreditCardInfo;
DROP TABLE IF EXISTS Payments;
DROP TABLE IF EXISTS PaymentMethods;
DROP TABLE IF EXISTS PropertyOwners;
DROP TABLE IF EXISTS Owners;
DROP TABLE IF EXISTS Pricing;
DROP TABLE IF EXISTS Property;
DROP TABLE IF EXISTS Tenants;
DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS RolePermissions;
DROP TABLE IF EXISTS Permissions;
DROP TABLE IF EXISTS Roles;
DROP TABLE IF EXISTS Vendors;
GO